# Site settings
title: "That Damn Cabbage"
author: "Robin Howard"
email: "robin@rhoward.id.au"

description: >
  Blog and portfolio nexus for Robin Howard, esteemed TypeScript/Ruby/Haskell/Rust-using programmer nitwit.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rhoward.id.au" # the base hostname & protocol for your site
permalink: "/blog/:year/:month/:title/" # Compatibility with previous Jekyll 0.x site

future: true # include content marked with a date in the future

twitter_username: "buzzyrobin"
github_username:  "damncabbage"
mastodon_domain: "chaos.social"
mastodon_username: "buzzyrobin"
speakerdeck_username: "damncabbage"

# Build settings
markdown: "kramdown" # was: "redcarpet" # was: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "rouge"
  coderay_line_numbers: nil
#highlighter: "coderay"
#redcarpet:
#  extensions:
#  - "with_toc_data" # Auto-add IDs to headings


# Avoid picking up the template posts inside the jekyll gem itself.
exclude: ["vendor"]

collections:
  talks:
    output: true
    permalink: "/talks/:path/" # /talks/2015/02/foo_bar_baz/

  series:
    output: true

  # TODO:
  #projects:
